apiVersion: v1
kind: Service
metadata:
  name: vprodb # Must nbe match with the application properties file
  labels:
    app: vprodbservice
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: vprodbpods
  type: ClusterIP